version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./myapp:/app
      - ./myapp/ios/Pods:/app/ios/Pods  # Persist Pods across runs
    command: ["npm", "install"]